# プログラムからは Rails.application.secrets.facebook_id のようにアクセスできます。
 
# 開発用アプリのKeyを直接設定
default: &default
  twitter_consumer_key: 'p1kXruMcvR9qzaANAphm3sgav'
  twitter_consumer_secret: 'rLLYwiOdTqq7HJNoSQLiqhMEQ55IKGriax9mlYKIj3AKGKgXCl'
 
development:
  <<: *default
 
test:
  <<: *default
 
# 本番環境では環境変数にKEYを登録します
production:
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
